-- Drop existing tables if they exist
DROP TABLE IF EXISTS public.todos;
DROP TABLE IF EXISTS public.categories;

-- Create categories table
CREATE TABLE public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  color text default 'bg-blue-500',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint name_length check (char_length(name) > 0)
);

-- Create index for user_id on categories
CREATE INDEX categories_user_id_idx ON public.categories(user_id);

-- Enable RLS for categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for categories
CREATE POLICY "Users can view their own categories"
  ON public.categories
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own categories"
  ON public.categories
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own categories"
  ON public.categories
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own categories"
  ON public.categories
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create todos table
CREATE TABLE public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text not null,
  is_complete boolean default false,
  status text default 'not_started' check (status in ('not_started', 'in_progress', 'completed')),
  category_id bigint references public.categories(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint task_length check (char_length(task) > 0)
);

-- Create indexes for faster queries
CREATE INDEX todos_user_id_idx ON public.todos(user_id);
CREATE INDEX todos_category_id_idx ON public.todos(category_id);
CREATE INDEX todos_is_complete_idx ON public.todos(is_complete);

-- Enable RLS for todos
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for todos
CREATE POLICY "Users can view their own todos"
  ON public.todos
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own todos"
  ON public.todos
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own todos"
  ON public.todos
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own todos"
  ON public.todos
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create function to update updated_at timestamp for categories
CREATE OR REPLACE FUNCTION public.update_categories_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for categories updated_at
CREATE TRIGGER categories_updated_at_trigger
  BEFORE UPDATE ON public.categories
  FOR EACH ROW
  EXECUTE FUNCTION public.update_categories_updated_at();

-- Create function to update updated_at timestamp for todos
CREATE OR REPLACE FUNCTION public.update_todos_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for todos updated_at
CREATE TRIGGER todos_updated_at_trigger
  BEFORE UPDATE ON public.todos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_todos_updated_at();
