-- Drop existing todos table if it exists
DROP TABLE IF EXISTS public.todos;

-- Create new todos table with updated schema
CREATE TABLE public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text check (char_length(task) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for user_id for faster queries
CREATE INDEX todos_user_id_idx ON public.todos(user_id);

-- Enable RLS (Row Level Security)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Create RLS policy: Users can only see their own todos
CREATE POLICY "Enable read access for users based on user_id" 
  ON public.todos 
  FOR SELECT 
  USING (auth.uid() = user_id);

-- Create RLS policy: Users can only insert their own todos
CREATE POLICY "Enable insert access for users based on user_id" 
  ON public.todos 
  FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Create RLS policy: Users can only update their own todos
CREATE POLICY "Enable update access for users based on user_id" 
  ON public.todos 
  FOR UPDATE 
  USING (auth.uid() = user_id);

-- Create RLS policy: Users can only delete their own todos
CREATE POLICY "Enable delete access for users based on user_id" 
  ON public.todos 
  FOR DELETE 
  USING (auth.uid() = user_id);
